name: GraalVM CI

on: [push]

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build with Maven
      run: |
        wget -q https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.0/graalvm-ce-java11-darwin-amd64-19.3.0.tar.gz
        tar xzf graalvm-ce-java11-darwin-amd64-19.3.0.tar.gz
        export JAVA_HOME="$(pwd)/graalvm-ce-java11-19.3.0/Contents/Home/"
        ${JAVA_HOME}/bin/gu install native-image
        ./mvnw --batch-mode package
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build with Maven
      run: |
        wget -q https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.0/graalvm-ce-java11-linux-amd64-19.3.0.tar.gz
        tar xzf graalvm-ce-java11-linux-amd64-19.3.0.tar.gz
        export JAVA_HOME="$(pwd)/graalvm-ce-java11-19.3.0"
        ${JAVA_HOME}/bin/gu install native-image
        ./mvnw --batch-mode package
  windows:
    runs-on: windows-latest
    steps:
    - run: choco install graalvm --version=19.3.0 --no-progress
    - name: Build native-image.exe
      shell: cmd
      working-directory: C:\Program Files\GraalVM\graalvm-ce-java11-19.3.0
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\bin\vcvars64.bat" & .\bin\native-image.cmd -jar lib\graalvm\svm-driver.jar "-H:Path=C:\Program Files\GraalVM\graalvm-ce-java11-19.3.0\bin"
    - name: Build with Maven
      shell: cmd
      env:
        JAVA_HOME: C:\Program Files\GraalVM\graalvm-ce-java11-19.3.0
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\bin\vcvars64.bat" & .\mvnw -X --batch-mode package --file pom.xml
