name: GraalVM CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - run: choco install graalvm --version=19.3.0 --no-progress
    - name: Build with Maven
      env:
        JAVA_HOME: C:\Program Files\GraalVM\graalvm-ce-java11-19.3.0
        MAVEN_OPTS: --add-exports=java.base/jdk.internal.module=ALL-UNNAMED
      run: |
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.BAT"
        mvnw -X --batch-mode package --file pom.xml
