name: GraalVM CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - run: reg query HKLM\SOFTWARE\Wow6432Node\Microsoft\NET Framework Setup\NDP\v4\Client\Version
    - run: reg query HKLM\SOFTWARE\Wow6432Node\Microsoft\NET Framework Setup\NDP\v4\Full\Version
    - run: wmic product get name
    - run: choco install sysinternals
    - run: psinfo -s
    - run: choco install windows-sdk-7.1 --no-progress --verbose
    - run: choco install graalvm --version=19.1.0 --no-progress
    - name: Build with Maven
      env:
        JAVA_HOME: C:\Program Files\GraalVM\graalvm-ce-19.1.0
      run: |
        call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd"
        mvn --batch-mode package --file pom.xml
