name: GraalVM CI

on: [push]

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build with Maven
      run: |
        wget -q https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.0/graalvm-ce-java11-darwin-amd64-19.3.0.tar.gz
        tar xzf graalvm-ce-java11-darwin-amd64-19.3.0.tar.gz
        export JAVA_HOME="$(pwd)/graalvm-ce-java11-19.3.0/Contents/Home/"
        ${JAVA_HOME}/bin/gu install native-image
        ./mvnw --batch-mode package
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build with Maven
      run: |
        wget -q https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.0/graalvm-ce-java11-linux-amd64-19.3.0.tar.gz
        tar xzf graalvm-ce-java11-linux-amd64-19.3.0.tar.gz
        export JAVA_HOME="$(pwd)/graalvm-ce-java11-19.3.0"
        ${JAVA_HOME}/bin/gu install native-image
        ./mvnw --batch-mode package
