name: GraalVM CI

on:
  push:
  schedule:
    - cron: '50 6 21 * *'
jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: |
        wget -q https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.2.0/graalvm-ce-java11-darwin-amd64-20.2.0.tar.gz
        tar xzf graalvm-ce-java11-darwin-amd64-20.2.0.tar.gz
        export JAVA_HOME="$(pwd)/graalvm-ce-java11-20.2.0/Contents/Home/"
        ${JAVA_HOME}/bin/gu install native-image
        brew install upx
        ./mvnw \
          --batch-mode \
          -Dsha1="${GITHUB_SHA}" \
          -Drevision="${GITHUB_SHA}" \
          package
        ./target/newlinechecker-mac-*
        upx --brute target/newlinechecker-mac-*
        ./target/newlinechecker-mac-*
        mkdir target/artifacts
        cp target/newlinechecker-* target/artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: newlinechecker artifacts from ${{runner.os}} build
        path: target/artifacts
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: |
        wget -q https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.2.0/graalvm-ce-java11-linux-amd64-20.2.0.tar.gz
        tar xzf graalvm-ce-java11-linux-amd64-20.2.0.tar.gz
        export JAVA_HOME="$(pwd)/graalvm-ce-java11-20.2.0"
        ${JAVA_HOME}/bin/gu install native-image
        sudo apt-get install upx-ucl
        ./mvnw \
          --batch-mode \
          -Dsha1="${GITHUB_SHA}" \
          -Drevision="${GITHUB_SHA}" \
          package
        ./target/newlinechecker-linux-*        
        # see https://github.com/upx/upx/issues/405#issuecomment-688342502
        # re-add upx when updating from graalvm 20.2.0 to 20.3.0
        # upx --brute target/newlinechecker-linux-*
        ./target/newlinechecker-linux-*
        mkdir target/artifacts
        cp target/newlinechecker-* target/artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: newlinechecker artifacts from ${{runner.os}} build
        path: target/artifacts
  windows:
    runs-on: windows-latest
    env:
      VCVARS_BAT: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - run: choco install graalvm --version=20.2.0 --no-progress
    - run: choco install upx --version=3.96 --no-progress
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: .m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      shell: cmd
      env:
        JAVA_HOME: C:\Program Files\GraalVM\graalvm-ce-java11-20.2.0
      run: |
        call "%JAVA_HOME%\bin\gu" install native-image
        call "%VCVARS_BAT%"
        call .\mvnw --batch-mode -Dsha1="%GITHUB_SHA%" -Drevision="%GITHUB_SHA%" --settings .\.mvn\github-actions-windows-maven-settings.xml  package
        .\target\newlinechecker-windows-%GITHUB_SHA%
        upx --brute target/newlinechecker-windows-*
        .\target\newlinechecker-windows-%GITHUB_SHA%
        mkdir target\artifacts
        copy target\newlinechecker-* target\artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: newlinechecker artifacts from ${{runner.os}} build
        path: target/artifacts
