name: GraalVM CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - run: wmic product get name
    - run: choco install sysinternals
    - run: psinfo -s
    - run: choco install rktools.2003
    - run: choco install windows-sdk-10 --no-progress --verbose
    - run: |
        SET WindowsSdkVersion=
        FOR /F "tokens=1,2*" %%i in ('REG QUERY "%1\SOFTWARE\Microsoft\Microsoft SDKs\Windows" /V "CurrentVersion"') DO (
          IF "%%i"=="CurrentVersion" (
            SET "WindowsSdkVersion=%%k"
          )
        )
        IF "%WindowsSdkVersion%"=="" EXIT /B 1
        SET WindowsSdkPath=
        FOR /F "tokens=1,2*" %%i in ('REG QUERY "HKLM\SOFTWARE\Microsoft\Microsoft SDKs\Windows\%WindowsSdkVersion%" /V InstallationFolder') DO (
          IF "%%i"=="InstallationFolder" (
            SET "WindowsSdkPath=%%k"
          )
        )
        IF "%WindowsSdkPath%"=="" EXIT /B 1
    - run: choco install graalvm --version=19.1.0 --no-progress
    - name: Build with Maven
      env:
        JAVA_HOME: C:\Program Files\GraalVM\graalvm-ce-19.1.0
      run: |
        call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd"
        mvn --batch-mode package --file pom.xml
