name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      env:
        REVISION: ${{ github.ref }}
      run: |
        wget -q https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.2.0/graalvm-ce-java11-darwin-amd64-20.2.0.tar.gz
        tar xzf graalvm-ce-java11-darwin-amd64-20.2.0.tar.gz
        export JAVA_HOME="$(pwd)/graalvm-ce-java11-20.2.0/Contents/Home/"
        ${JAVA_HOME}/bin/gu install native-image
        brew install upx
        ./mvnw \
          --batch-mode \
          -Dsha1="${GITHUB_SHA}" \
          -Drevision="${REVISION}" \
          package
        "./target/newlinechecker-mac-${REVISION}"
        upx --brute "target/newlinechecker-mac-${REVISION}"
        "./target/newlinechecker-mac-${REVISION}"
        mkdir target/artifacts
        cp target/newlinechecker-* target/artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: newlinechecker artifacts from ${{runner.os}} build
        path: target/artifacts
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      env:
        REVISION: ${{ github.ref }}
      run: |
        wget -q https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.2.0/graalvm-ce-java11-linux-amd64-20.2.0.tar.gz
        tar xzf graalvm-ce-java11-linux-amd64-20.2.0.tar.gz
        export JAVA_HOME="$(pwd)/graalvm-ce-java11-20.2.0"
        ${JAVA_HOME}/bin/gu install native-image
        sudo apt-get install upx-ucl
        ./mvnw \
          --batch-mode \
          -Dsha1="${GITHUB_SHA}" \
          -Drevision="${REVISION}" \
          package
        "./target/newlinechecker-linux-${REVISION}"
        # see https://github.com/upx/upx/issues/405#issuecomment-688342502
        # re-add upx when updating from graalvm 20.2.0 to 20.3.0
        # upx --brute "target/newlinechecker-linux-${REVISION}"
        "./target/newlinechecker-linux-${REVISION}"
        mkdir target/artifacts
        cp target/newlinechecker-* target/artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: newlinechecker artifacts from ${{runner.os}} build
        path: target/artifacts
  windows:
    runs-on: windows-latest
    env:
      VCVARS_BAT: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - run: choco install graalvm --version=20.2.0 --no-progress
    - run: choco install upx --version=3.96 --no-progress
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: .m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      shell: cmd
      env:
        JAVA_HOME: C:\Program Files\GraalVM\graalvm-ce-java11-20.2.0
        REVISION: ${{ github.ref }}
      run: |
        call "%JAVA_HOME%\bin\gu" install native-image
        call "%VCVARS_BAT%"
        call .\mvnw --batch-mode -Dsha1="%GITHUB_SHA%" -Drevision="%REVISION%" --settings .\.mvn\github-actions-windows-maven-settings.xml  package
        .\target\newlinechecker-windows-%REVISION%.exe
        upx --brute target/newlinechecker-windows-%REVISION%.exe
        .\target\newlinechecker-windows-%REVISION%.exe
        mkdir target\artifacts
        copy target\newlinechecker-* target\artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: newlinechecker artifacts from ${{runner.os}} build
        path: target/artifacts
  release:
    runs-on: ubuntu-latest
    needs: [macos, ubuntu, windows]
    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
    - name: Build project
      run: |
        zip --junk-paths my-artifact README.md
    - run: ls -lsa *
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./my-artifact.zip
        asset_name: my-artifact.zip
        asset_content_type: application/zip
